language: generic

matrix:
  include:
    - script:
        - ./test_xcode.sh
      env: JOB=Xcode
      os: osx
      osx_image: xcode8.3
      before_install:
        - rvm list
        - rvm install $(cat .ruby-version)
        - bundle install
        - cd Utility
        - ./brew_update.sh
        - ./generate_xcodeproj.sh
    - script:
        - ./test.sh
        - ./lint.sh cli
      env: JOB=SwiftPM
      os: osx
      osx_image: xcode8.3
      before_install:
        - rvm list
        - rvm install $(cat .ruby-version)
        - bundle install
        - cd Utility
        - ./brew_update.sh
    - script:
        - docker run -it -d -P mockingbird bash -c "cd Utility && bash test.sh"
      env: JOB=Linux
      sudo: required
      services: docker
      before_install:
        - cd Utility
        - ./setup_docker_server.sh
        - docker ps -a
